-- Script legado descontinuado.
-- O projeto foi migrado para PostgreSQL.
--
-- Use os arquivos abaixo para inicializar o banco:
-- 1) backend/database/schema.sql
-- 2) backend/database/seed.sql
--
-- Exemplo com psql:
-- psql -h localhost -U postgres -d copal -f backend/database/schema.sql
-- psql -h localhost -U postgres -d copal -f backend/database/seed.sql
